<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<div> 넘길 정보 아무거나 적어서 push 해주세요 </div>
	<p>
	ALTER SEQUENCE SEQ_CHAT_CONTENTS INCREMENT BY 200;
ALTER SEQUENCE SEQ_MARKET_DETAIL_IMG_IDX INCREMENT BY 200;
ALTER SEQUENCE SEQ_MARKET_IDX INCREMENT BY 200;
ALTER SEQUENCE SEQ_MARKET_OPTION_PRICE_IDX INCREMENT BY 200;
ALTER SEQUENCE SEQ_MARKET_SCHEDULE_IDX INCREMENT BY 700;
ALTER SEQUENCE SEQ_MARKET_THUMBNAIL_IMG_IDX INCREMENT BY 200;
	</p>
</body>
</html>